language:
 - c

before_install:
# install latest OS fixes
 - sudo apt-get -qq update
# install DOSEMU
 - sudo apt-get install -y dosemu

before_script:
# initialize OW build environment variables
 - . $OWROOT/cmnvars.sh

script:
 - . $OWROOT/build.sh

after_failure:
# after failure transfer log files back to GitHub repository
 - cd $HOME
# configure Git
 - git config --global user.email "travis@travis-ci.org"
 - git config --global user.name "Travis CI"
 - git config --global push.default simple
# clone GitHub repository
 - git clone --quiet --branch=master https://${GITHUB_TOKEN}@github.com/open-watcom/travis-ci-ow-builds.git
# copy new log files to git repository tree
 - cd travis-ci-ow-builds
 - if [ ! -d bld ]; then mkdir bld; fi
 - if [ ! -d docs ]; then mkdir docs; fi
 - cp $OWROOT/bld/*.log bld/
 - cp $OWROOT/docs/*.log docs/
# commit new log files to GitHub repository
 - git add -f .
 - git commit -m "Travis CI build $TRAVIS_BUILD_NUMBER - log files"
 - git push -f origin
